doEliteMobsLoot: true
doMMORPGColorsForItems: true
preventCustomItemPlacement: true
itemLoreStructures:
  - 'Â§7Â§mÂ§l---------Â§7<Â§lè£…å¤‡è¯¦æƒ…Â§7>Â§mÂ§l---------'
  - 'Â§7Â§fç‰©å“$itemLevelçº§Â§7|å£°æœ›Â§6$prestigeLevelçº§'
  - '$soulbindInfo'
  - '$itemSource'
  - '$ifLoreÂ§7Â§mÂ§l-----------Â§7< Â§fÂ§lLoreÂ§7 >Â§mÂ§l-----------'
  - '$customLore'
  - '$ifEnchantmentsÂ§7Â§mÂ§l--------Â§7<Â§9Â§lé™„é­”Â§7>Â§mÂ§l--------'
  - '$enchantments'
  - '$eliteEnchantments'
  - '$ifCustomEnchantmentsÂ§7Â§mÂ§l------Â§7< Â§3Â§lè‡ªå®šä¹‰é™„é­”Â§7 >Â§mÂ§l------'
  - '$customEnchantments'
  - '$ifPotionEffectsÂ§7Â§mÂ§l----------Â§7< Â§5Â§læ•ˆæœÂ§7 >Â§mÂ§l----------'
  - '$potionEffect'
  - 'Â§7Â§lÂ§m-----------------------------'
  - '$loreResaleValue'
shopSourceItemLores: '&7ä»å•†åº—è´­ä¹°è·å¾—'
mobSourceItemLores: '&7ä»ç²¾è‹±$mobèº«ä¸Šæ å¤ºè€Œå¾—'
loreWorths: '&7ä»·å€¼$worth $currencyName'
loreResaleValues: '&7å‡ºå”®å¯è·å¾—$resale $currencyName'
flatDropRateV2: 0.33
tierIncreaseDropRateV2: 0.0
proceduralItemDropWeight: 90.0
weighedItemDropWeight: 1.0
fixedItemDropWeight: 10.0
limitedItemDropWeight: 3.0
scalableItemDropWeight: 6.0
defaultLootMultiplier: 0.0
levelCapForDefaultLootMultiplier: 200
defaultExperienceMultiplier: 1.0
maximumLootTiers: 200
useEliteEnchantments: true
eliteEnchantmentLoreStrings: ç²¾è‹±
useHoesAsWeapons: false
enableRareItemParticleEffects: true
potionEffectOnHitTargetLore: '&4âš”â˜ '
potionEffectOnHitSelfLore: '&9âš”ğŸ›¡'
potionEffectContinuousLore: '&6âŸ²'
eliteEnchantmentLoreColor: '&9â—‡'
vanillaEnchantmentLoreColor: '&7â—‡'
customEnchantmentColor: '&3â—‡'
potionEffectLoreColor: '&5â—‡'
noSoulbindLore: '&7æœªç»‘å®šçµé­‚ï¼'
preventEliteItemEnchantment: true
preventEliteItemDiamondToNetheriteUpgrade: true
